// Copyright 2026, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

declare global {

    // wps.GulinEvent
    type GulinEventName = "blockclose" | "connchange" | "sysinfo" | "controllerstatus" | "builderstatus" | "builderoutput" | "gulinobj:update" | "blockfile" | "config" | "userinput" | "route:down" | "route:up" | "workspace:update" | "gulinai:ratelimit" | "gulinapp:appgoupdated" | "tsunami:updatemeta" | "gulinai:modeconfig" | "tab:indicator" | "block:jobstatus";

    type GulinEvent = {
        event: GulinEventName;
        scopes?: string[];
        sender?: string;
        persist?: number;
        data?: unknown;
    } & (
        { event: "blockclose"; data?: string; } | 
        { event: "connchange"; data?: ConnStatus; } | 
        { event: "sysinfo"; data?: TimeSeriesData; } | 
        { event: "controllerstatus"; data?: BlockControllerRuntimeStatus; } | 
        { event: "builderstatus"; data?: BuilderStatusData; } | 
        { event: "builderoutput"; data?: {[key: string]: any}; } | 
        { event: "gulinobj:update"; data?: GulinObjUpdate; } | 
        { event: "blockfile"; data?: WSFileEventData; } | 
        { event: "config"; data?: WatcherUpdate; } | 
        { event: "userinput"; data?: UserInputRequest; } | 
        { event: "route:down"; data?: null; } | 
        { event: "route:up"; data?: null; } | 
        { event: "workspace:update"; data?: null; } | 
        { event: "gulinai:ratelimit"; data?: RateLimitInfo; } | 
        { event: "gulinapp:appgoupdated"; data?: null; } | 
        { event: "tsunami:updatemeta"; data?: AppMeta; } | 
        { event: "gulinai:modeconfig"; data?: AIModeConfigUpdate; } | 
        { event: "tab:indicator"; data?: TabIndicatorEventData; } | 
        { event: "block:jobstatus"; data?: BlockJobStatusData; }
    );

}

export {}
